# Generated by Django 3.0.3 on 2020-02-28 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0002_auto_20200228_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleclase',
            name='vehiculo',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='clases.Vehiculo'),
            preserve_default=False,
        ),
    ]
