# Generated by Django 3.0.3 on 2020-02-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='creado_por',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipo_de_id',
            field=models.CharField(choices=[('T.I', 'Tarjeta de identidad'), ('C.C', 'Cedula de ciudadania'), ('C.E', 'Cedula de Extrangeria')], default='C.C', max_length=3, verbose_name='Tipo de identificación'),
        ),
    ]
